#pragma once

#include <vector>
#include <string>
#include <array>
#include <cmath>
#include "PRNG.h"
#include "Scales.h"

// Zone colors for rendering (same 16 as web version)
inline const std::array<uint32_t, 16> ZONE_COLORS = {
    0xFFE24B4A, 0xFFD85A30, 0xFFEF9F27, 0xFF639922,
    0xFF1D9E75, 0xFF378ADD, 0xFF534AB7, 0xFFD4537E,
    0xFF5DCAA5, 0xFF85B7EB, 0xFFAFA9EC, 0xFFF0997B,
    0xFFED93B1, 0xFF97C459, 0xFFFAC775, 0xFF888780
};

struct Zone
{
    float cx, cy;       // center (0-1 normalized)
    float hw, hh;       // half-width, half-height
    int midi;           // MIDI note number
    int colorIndex;
    int placementOrder = 0; // order in which zone was placed (for arp first-placed mode)
};

struct Ball
{
    float x, y;
    float vx, vy;
    std::vector<std::pair<float,float>> trail;
};

// Persistent state — serializable, maps to DAW parameters
struct PersistentState
{
    int gravity      = 20;    // 0-100
    int bounce       = 90;    // 50-100
    int friction     = 4;     // 0-50
    int speed        = 40;    // 5-100
    int ballCount    = 2;     // 0-16
    int ballSize     = 7;     // 3-18
    int minEnergy    = 25;    // 0-80
    bool solidZones  = true;
    bool ballCollide = false;
    int gateTime     = 250;   // ms (20-2000)

    int momentum     = 0;     // 0-100
    int jitter       = 0;     // 0-100

    int fanAmount    = 0;     // 0-100
    int fanSpeed     = 30;    // 0-100
    int fanDirection = 0;     // 0=N, 1=S, 2=E, 3=W, 4=Random

    int scaleRoot    = 0;     // 0-11
    int scaleName    = 0;     // index into getAllScales()

    int randomPitch        = 0;   // 0-100
    int randomOctaveChance = 0;   // 0-100
    int randomOctaveAmount = 1;   // 1-3
    int randomVelocity     = 0;   // 0-100
    int velocityFloor      = 10;  // 0-100 minimum velocity

    // Arpeggiator
    bool arpEnabled    = false;
    bool arpSync       = true;     // true = sync to host BPM divisions
    int  arpDivision   = 5;        // index into ArpDivision enum (default 1/8)
    int  arpRateMs     = 200;      // free-running rate in ms (10-4000)
    int  arpPlayMode   = 1;        // index into ArpPlayMode enum (default Up)
    bool arpPendulum   = false;
    int  arpRatchet    = 0;        // 0-16
    bool arpUseRandomization = false;

    std::vector<Zone> zones;
};

// Arp runtime state
struct ArpState
{
    int sequencePos = 0;
    int direction = 1;          // 1=forward, -1=backward (pendulum)
    int ratchetCount = 0;
    double sampleAccumulator = 0.0;  // sample-accurate timing
    std::vector<int> sequence;       // sorted zone indices
    int lastZoneCount = 0;
    bool needsRebuild = true;
};

// Transient state — runtime only
struct TransientState
{
    bool running = true;
    std::vector<Ball> balls;
    std::vector<float> zoneFlash;
    std::vector<float> zoneLockout;
    int selectedZone = -1;
    PRNG prng{42};
    float tickCount = 0.0f;
    int nextPlacementOrder = 0;
    ArpState arpState;
};

// MIDI event generated by physics
struct PhysicsEvent
{
    int midi;
    float velocity;   // 0-1
    int zoneIndex;
};

namespace StateUtils
{
    inline std::vector<Zone> createDefaultZones()
    {
        using namespace Scales;
        return {
            { 0.15f, 0.30f, 0.06f, 0.04f, nameToMidi("C", 4), 0,  0 },
            { 0.35f, 0.20f, 0.03f, 0.07f, nameToMidi("E", 4), 1,  1 },
            { 0.55f, 0.35f, 0.05f, 0.03f, nameToMidi("G", 4), 2,  2 },
            { 0.75f, 0.25f, 0.04f, 0.05f, nameToMidi("C", 5), 3,  3 },
            { 0.25f, 0.55f, 0.07f, 0.03f, nameToMidi("D", 4), 4,  4 },
            { 0.50f, 0.60f, 0.03f, 0.08f, nameToMidi("F", 4), 5,  5 },
            { 0.70f, 0.55f, 0.05f, 0.05f, nameToMidi("A", 4), 6,  6 },
            { 0.15f, 0.75f, 0.04f, 0.06f, nameToMidi("G", 3), 7,  7 },
            { 0.40f, 0.80f, 0.06f, 0.03f, nameToMidi("B", 3), 8,  8 },
            { 0.65f, 0.78f, 0.03f, 0.05f, nameToMidi("B", 4), 9,  9 },
            { 0.85f, 0.50f, 0.04f, 0.09f, nameToMidi("E", 5), 10, 10 },
            { 0.90f, 0.15f, 0.03f, 0.04f, nameToMidi("G", 5), 11, 11 },
            { 0.10f, 0.12f, 0.05f, 0.03f, nameToMidi("C", 3), 12, 12 },
            { 0.45f, 0.45f, 0.04f, 0.04f, nameToMidi("G", 4), 13, 13 },
        };
    }

    inline PersistentState createDefaultPersistentState()
    {
        PersistentState s;
        s.zones = createDefaultZones();
        return s;
    }

    inline std::vector<Ball> createBalls(const PersistentState& p)
    {
        float speedFactor = p.speed / 100.0f;
        std::vector<Ball> balls;
        for (int i = 0; i < p.ballCount; i++)
        {
            float angle = (3.14159265f * 2.0f * i) / p.ballCount + 3.14159265f * 0.25f;
            float baseSpeed = 0.003f + speedFactor * 0.007f;
            Ball b;
            b.x = 0.5f;
            b.y = 0.35f;
            b.vx = std::cos(angle) * baseSpeed;
            b.vy = std::sin(angle) * baseSpeed;
            balls.push_back(b);
        }
        return balls;
    }

    inline TransientState createTransientState(const PersistentState& p)
    {
        TransientState t;
        t.balls = createBalls(p);
        t.zoneFlash.resize(p.zones.size(), 0.0f);
        t.zoneLockout.resize(p.zones.size(), 0.0f);
        t.nextPlacementOrder = static_cast<int>(p.zones.size());
        return t;
    }

    inline int nextColorIndex(const std::vector<Zone>& zones)
    {
        if (zones.empty()) return 0;
        int maxIdx = -1;
        for (auto& z : zones)
            maxIdx = std::max(maxIdx, z.colorIndex);
        return (maxIdx + 1) % 16;
    }
}
